grails-app/domain/com/myapp/CartProduct.groovy
package com.myapp

class CartProduct {

    Cart cart
    Product product
    Integer howMany

    static constraints = {
    }
}

grails-app/views/cartProduct/_form.gsp
<%@ page import="com.myapp.CartProduct" %>



<div class="fieldcontain ${hasErrors(bean: cartProductInstance, field: 'cart', 'error')} required">
	<label for="cart">
		<g:message code="cartProduct.cart.label" default="Cart" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="cart" name="cart.id" from="${com.myapp.Cart.list()}" optionKey="id" required="" value="${cartProductInstance?.cart?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: cartProductInstance, field: 'howMany', 'error')} required">
	<label for="howMany">
		<g:message code="cartProduct.howMany.label" default="How Many" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="howMany" type="number" value="${cartProductInstance.howMany}" required=""/>
</div>

<div class="fieldcontain ${hasErrors(bean: cartProductInstance, field: 'product', 'error')} required">
	<label for="product">
		<g:message code="cartProduct.product.label" default="Product" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="product" name="product.id" from="${com.myapp.Product.list()}" optionKey="id" required="" value="${cartProductInstance?.product?.id}" class="many-to-one"/>
</div>

grails-app/views/cartProduct/create.gsp
<%@ page import="com.myapp.CartProduct" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'cartProduct.label', default: 'CartProduct')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-cartProduct" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-cartProduct" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${cartProductInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${cartProductInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form action="save" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/cartProduct/edit.gsp
<%@ page import="com.myapp.CartProduct" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'cartProduct.label', default: 'CartProduct')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-cartProduct" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-cartProduct" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${cartProductInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${cartProductInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form method="post" >
				<g:hiddenField name="id" value="${cartProductInstance?.id}" />
				<g:hiddenField name="version" value="${cartProductInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/cartProduct/list.gsp
<%@ page import="com.myapp.CartProduct" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'cartProduct.label', default: 'CartProduct')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-cartProduct" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-cartProduct" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<th><g:message code="cartProduct.cart.label" default="Cart" /></th>
					
						<g:sortableColumn property="howMany" title="${message(code: 'cartProduct.howMany.label', default: 'How Many')}" />
					
						<th><g:message code="cartProduct.product.label" default="Product" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${cartProductInstanceList}" status="i" var="cartProductInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${cartProductInstance.id}">${fieldValue(bean: cartProductInstance, field: "cart")}</g:link></td>
					
						<td>${fieldValue(bean: cartProductInstance, field: "howMany")}</td>
					
						<td>${fieldValue(bean: cartProductInstance, field: "product")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${cartProductInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/cartProduct/show.gsp
<%@ page import="com.myapp.CartProduct" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'cartProduct.label', default: 'CartProduct')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-cartProduct" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-cartProduct" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list cartProduct">
			
				<g:if test="${cartProductInstance?.cart}">
				<li class="fieldcontain">
					<span id="cart-label" class="property-label"><g:message code="cartProduct.cart.label" default="Cart" /></span>
					
						<span class="property-value" aria-labelledby="cart-label"><g:link controller="cart" action="show" id="${cartProductInstance?.cart?.id}">${cartProductInstance?.cart?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${cartProductInstance?.howMany}">
				<li class="fieldcontain">
					<span id="howMany-label" class="property-label"><g:message code="cartProduct.howMany.label" default="How Many" /></span>
					
						<span class="property-value" aria-labelledby="howMany-label"><g:fieldValue bean="${cartProductInstance}" field="howMany"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${cartProductInstance?.product}">
				<li class="fieldcontain">
					<span id="product-label" class="property-label"><g:message code="cartProduct.product.label" default="Product" /></span>
					
						<span class="property-value" aria-labelledby="product-label"><g:link controller="product" action="show" id="${cartProductInstance?.product?.id}">${cartProductInstance?.product?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form>
				<fieldset class="buttons">
					<g:hiddenField name="id" value="${cartProductInstance?.id}" />
					<g:link class="edit" action="edit" id="${cartProductInstance?.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>