grails-app/domain/com/myapp/Cart.groovy
package com.myapp

class Cart {

    static belongsTo = [user: User]

    static constraints = {
        user(nullable: true)
    }
}

grails-app/controllers/com/myapp/CartController.groovy
package com.myapp

import org.springframework.dao.DataIntegrityViolationException

class CartController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def cartService

    def index() {
        redirect(action: "show")
    }

    def show() {
        def cartInstance
        if (session.cartId) {
            cartInstance = Cart.get(session.cartId)
        } else {
            cartInstance = new Cart()
            cartInstance.save(failOnError: true, flush: true)
            session.cartId = cartInstance.id

        }
        [cartInstance: cartInstance, cartProducts:cartService.getCartProducts(cartInstance.id), totalCost: cartService.getCartTotalPrice(cartInstance)]
    }

    def purchase() {
        def cartInstance = Cart.get(session.cartId)
        if (!cartInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'cart.label', default: 'Cart'), id])
            redirect(action: "show")
            return
        }
        redirect(controller: "customerOrder", action: "create")
     }


}

grails-app/views/cart/_cartContents.gsp
<table>
     <thead>
         <tr>
             <td>Product<td/>
             <td>Volume<td/>
         </tr>
     </thead>
     <tbody>
     <g:each in="${cartProducts}" status="i" var="cartProduct">
         <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
         <td>${cartProduct.product}</td>
         <td>${cartProduct.howMany}</td>
         </tr>
     </g:each>
     </tbody>
 </table>

grails-app/views/cart/_form.gsp
<%@ page import="com.myapp.Cart" %>



<div class="fieldcontain ${hasErrors(bean: cartInstance, field: 'user', 'error')} required">
	<label for="user">
		<g:message code="cart.user.label" default="User" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="user" name="user.id" from="${com.myapp.User.list()}" optionKey="id" required="" value="${cartInstance?.user?.id}" class="many-to-one"/>
</div>

grails-app/views/cart/create.gsp
<%@ page import="com.myapp.Cart" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'cart.label', default: 'Cart')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-cart" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-cart" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${cartInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${cartInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form action="save" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/cart/edit.gsp
<%@ page import="com.myapp.Cart" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'cart.label', default: 'Cart')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-cart" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-cart" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${cartInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${cartInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form method="post" >
				<g:hiddenField name="id" value="${cartInstance?.id}" />
				<g:hiddenField name="version" value="${cartInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/cart/list.gsp
<%@ page import="com.myapp.Cart" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'cart.label', default: 'Cart')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-cart" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-cart" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<th><g:message code="cart.user.label" default="User" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${cartInstanceList}" status="i" var="cartInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${cartInstance.id}">${fieldValue(bean: cartInstance, field: "user")}</g:link></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${cartInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/cart/show.gsp
<%@ page import="com.myapp.Cart" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'cart.label', default: 'Cart')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<div id="show-cart" class="content scaffold-show" role="main">
			<h1>Cart</h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>

            <g:if test="${cartProducts}">
                <g:render template="cartContents"/>
                <h1>Total: ${totalCost}</h1>
                <g:form>
                    <fieldset class="buttons">
                        <g:hiddenField name="id" value="${cartInstance?.id}" />
                        <g:actionSubmit class="button-link" action="purchase" value="Buy It!"  />
                    </fieldset>
                </g:form>
              </g:if>
             <g:else>
                 <h1>Your cart is empty.</h1>
             </g:else>
		</div>
	</body>
</html>