grails-app/domain/com/myapp/CustomerOrderProduct.groovy
package com.myapp

class CustomerOrderProduct {

    CustomerOrder customerOrder
    Product product
    Integer howMany

    static constraints = {
    }
}

grails-app/views/customerOrderProduct/_form.gsp
<%@ page import="com.myapp.CustomerOrderProduct" %>



<div class="fieldcontain ${hasErrors(bean: customerOrderProductInstance, field: 'customerOrder', 'error')} required">
	<label for="customerOrder">
		<g:message code="customerOrderProduct.customerOrder.label" default="Customer Order" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="customerOrder" name="customerOrder.id" from="${com.myapp.CustomerOrder.list()}" optionKey="id" required="" value="${customerOrderProductInstance?.customerOrder?.id}" class="many-to-one"/>
</div>

<div class="fieldcontain ${hasErrors(bean: customerOrderProductInstance, field: 'howMany', 'error')} required">
	<label for="howMany">
		<g:message code="customerOrderProduct.howMany.label" default="How Many" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="howMany" type="number" value="${customerOrderProductInstance.howMany}" required=""/>
</div>

<div class="fieldcontain ${hasErrors(bean: customerOrderProductInstance, field: 'product', 'error')} required">
	<label for="product">
		<g:message code="customerOrderProduct.product.label" default="Product" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="product" name="product.id" from="${com.myapp.Product.list()}" optionKey="id" required="" value="${customerOrderProductInstance?.product?.id}" class="many-to-one"/>
</div>

grails-app/views/customerOrderProduct/create.gsp
<%@ page import="com.myapp.CustomerOrderProduct" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'customerOrderProduct.label', default: 'CustomerOrderProduct')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-customerOrderProduct" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-customerOrderProduct" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${customerOrderProductInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${customerOrderProductInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form action="save" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/customerOrderProduct/edit.gsp
<%@ page import="com.myapp.CustomerOrderProduct" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'customerOrderProduct.label', default: 'CustomerOrderProduct')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-customerOrderProduct" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-customerOrderProduct" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${customerOrderProductInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${customerOrderProductInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form method="post" >
				<g:hiddenField name="id" value="${customerOrderProductInstance?.id}" />
				<g:hiddenField name="version" value="${customerOrderProductInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" formnovalidate="" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/customerOrderProduct/list.gsp
<%@ page import="com.myapp.CustomerOrderProduct" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'customerOrderProduct.label', default: 'CustomerOrderProduct')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-customerOrderProduct" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-customerOrderProduct" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
				<thead>
					<tr>
					
						<th><g:message code="customerOrderProduct.customerOrder.label" default="Customer Order" /></th>
					
						<g:sortableColumn property="howMany" title="${message(code: 'customerOrderProduct.howMany.label', default: 'How Many')}" />
					
						<th><g:message code="customerOrderProduct.product.label" default="Product" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${customerOrderProductInstanceList}" status="i" var="customerOrderProductInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${customerOrderProductInstance.id}">${fieldValue(bean: customerOrderProductInstance, field: "customerOrder")}</g:link></td>
					
						<td>${fieldValue(bean: customerOrderProductInstance, field: "howMany")}</td>
					
						<td>${fieldValue(bean: customerOrderProductInstance, field: "product")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${customerOrderProductInstanceTotal}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/customerOrderProduct/show.gsp
<%@ page import="com.myapp.CustomerOrderProduct" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'customerOrderProduct.label', default: 'CustomerOrderProduct')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-customerOrderProduct" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-customerOrderProduct" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list customerOrderProduct">
			
				<g:if test="${customerOrderProductInstance?.customerOrder}">
				<li class="fieldcontain">
					<span id="customerOrder-label" class="property-label"><g:message code="customerOrderProduct.customerOrder.label" default="Customer Order" /></span>
					
						<span class="property-value" aria-labelledby="customerOrder-label"><g:link controller="customerOrder" action="show" id="${customerOrderProductInstance?.customerOrder?.id}">${customerOrderProductInstance?.customerOrder?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${customerOrderProductInstance?.howMany}">
				<li class="fieldcontain">
					<span id="howMany-label" class="property-label"><g:message code="customerOrderProduct.howMany.label" default="How Many" /></span>
					
						<span class="property-value" aria-labelledby="howMany-label"><g:fieldValue bean="${customerOrderProductInstance}" field="howMany"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${customerOrderProductInstance?.product}">
				<li class="fieldcontain">
					<span id="product-label" class="property-label"><g:message code="customerOrderProduct.product.label" default="Product" /></span>
					
						<span class="property-value" aria-labelledby="product-label"><g:link controller="product" action="show" id="${customerOrderProductInstance?.product?.id}">${customerOrderProductInstance?.product?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form>
				<fieldset class="buttons">
					<g:hiddenField name="id" value="${customerOrderProductInstance?.id}" />
					<g:link class="edit" action="edit" id="${customerOrderProductInstance?.id}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>